import { Drug, FrequencyOption } from '../types'

export const FREQUENCY_OPTIONS: FrequencyOption[] = [
  { value: 7, label: "Once weekly", shortLabel: "1×/week", description: "Standard protocol" },
  { value: 3.5, label: "Twice weekly", shortLabel: "2×/week", description: "Better stability" },
  { value: 3, label: "Every 3 days", shortLabel: "q3d", description: "Balanced" },
  { value: 2, label: "Every other day", shortLabel: "EOD", description: "Best stability" },
]

export const glpDrugs: Drug[] = [
  {
    id: "semaglutide",
    name: "Semaglutide",
    brandNames: "Ozempic, Wegovy",
    halfLife: 7,
    eliminationRate: 0.099,
    timeToSteadyState: "4-5 weeks",
    missedDoseWindow: "5 days",
    color: "blue",
    description: "~7-day half-life",
    receptors: "GLP-1",
    warnings: [
      "May affect absorption of oral medications",
      "Hold ≥2 months before planned conception",
    ],
    weeklyDoseOptions: [
      { value: 0.25, label: "0.25 mg", category: "Initial titration", protocol: "Wegovy start dose" },
      { value: 0.5, label: "0.5 mg", category: "Early titration", protocol: "Week 5-8" },
      { value: 1.0, label: "1.0 mg", category: "Maintenance", protocol: "Week 9-12+" },
      { value: 1.7, label: "1.7 mg", category: "High dose", protocol: "Week 13-16+" },
      { value: 2.4, label: "2.4 mg", category: "Maximum", protocol: "Week 17+" },
    ],
  },
  {
    id: "tirzepatide",
    name: "Tirzepatide",
    brandNames: "Mounjaro, Zepbound",
    halfLife: 5,
    eliminationRate: 0.1386,
    timeToSteadyState: "~4 weeks",
    missedDoseWindow: "4 days",
    color: "emerald",
    description: "~5-day half-life",
    receptors: "GIP + GLP-1",
    warnings: [
      "Reduces oral contraceptive exposure—use non-oral or add barrier for 4 weeks after start/increases",
      "Delayed gastric emptying—inform anesthesia/procedure teams",
      "Small HR increase (1-4 bpm mean); consider if baseline tachycardia",
      "Gallbladder disease risk—monitor symptoms",
    ],
    weeklyDoseOptions: [
      { value: 2.5, label: "2.5 mg", category: "Initial titration", protocol: "Zepbound weeks 1-4" },
      { value: 5.0, label: "5.0 mg", category: "Low maintenance", protocol: "Week 5-8" },
      { value: 7.5, label: "7.5 mg", category: "Medium maintenance", protocol: "Week 9-12" },
      { value: 10.0, label: "10.0 mg", category: "Medium-high maintenance", protocol: "Week 13-16" },
      { value: 12.5, label: "12.5 mg", category: "High dose", protocol: "Week 17-20" },
      { value: 15.0, label: "15.0 mg", category: "Maximum", protocol: "Week 21+" },
    ],
  },
  {
    id: "retatrutide",
    name: "Retatrutide",
    brandNames: "Investigational (Phase 2)",
    halfLife: 6,
    eliminationRate: 0.1155,
    timeToSteadyState: "4-5 weeks",
    missedDoseWindow: "Not established",
    color: "purple",
    description: "~6-day half-life",
    receptors: "GIP + GLP-1 + Glucagon",
    warnings: [
      "Investigational agent—not FDA approved",
      "Dose-dependent HR increase, peaks ~week 24 then declines",
      "Follow trial-style protocols with clinical oversight",
      "Limited long-term safety data",
    ],
    weeklyDoseOptions: [
      { value: 0.5, label: "0.5 mg", category: "Microdose", protocol: "Acclimation/metabolic support" },
      { value: 1.0, label: "1.0 mg", category: "Low microdose", protocol: "Trial weeks 1-4" },
      { value: 2.0, label: "2.0 mg", category: "Body composition", protocol: "Trial weeks 5-8" },
      { value: 4.0, label: "4.0 mg", category: "Medium dose", protocol: "Trial weeks 9-12" },
      { value: 8.0, label: "8.0 mg", category: "High dose", protocol: "Trial weeks 13-16" },
      { value: 12.0, label: "12.0 mg", category: "Maximum", protocol: "Trial weeks 17+" },
    ],
  },
]
